---

include:
  - project: veepee/vptech/ci-cd/container-image
    ref: 1-latest
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKERFILE_LINT_EXTRA: --ignore DL3013 --ignore DL3018
  MOLECULE_VERSION: 5.0.1
  DOCKER_BUILD_ARGS: "--build-arg MOLECULE_VERSION=${MOLECULE_VERSION}"
  TAG: "${MOLECULE_VERSION}-${CI_COMMIT_REF_SLUG/-//}"

...
