---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 5-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 3-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 4-latest
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog
...
