---

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.4.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.1.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.5.1
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.9.0
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${CI_COMMIT_REF_SLUG}-${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: ['3.0.8', '3.1.5', '3.2.4', '3.3.4', '3.4.0' ]

delete-feature:docker:
  variables:
    TAG: '${CI_COMMIT_REF_SLUG}-3.0.8 ${CI_COMMIT_REF_SLUG}-3.1.5 ${CI_COMMIT_REF_SLUG}-3.2.4 ${CI_COMMIT_REF_SLUG}-3.3.4 ${CI_COMMIT_REF_SLUG}-3.4.0'

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: ['3.0.8', '3.1.5', '3.2.4', '3.3.4', '3.4.0' ]
...
