---

include:
  - project: veepee/vptech/ci-cd/container-image
    ref: 1-latest
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKERFILE_LINT_EXTRA: --ignore DL3013 --ignore DL3018
  MOLECULE_VERSION: 4.0.3
  TAG: ${MOLECULE_VERSION}
  DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${MOLECULE_VERSION}
...
