---

stages:
  - lint
  - build
  - publish
  - release

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.4.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.1.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.3.3
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.8.0
    file: gitlab-ci.yml

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

## Feature build / publish / delete

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${CI_COMMIT_REF_SLUG}-${VERSION}"
  parallel:
    matrix:
      - NAME: ['test']
        VERSION: ['2.22', '3.0.6', '3.4.0' ]

delete-feature:docker:
  variables:
    TAG: '${CI_COMMIT_REF_SLUG}-2.22 ${CI_COMMIT_REF_SLUG}-3.0.6 ${CI_COMMIT_REF_SLUG}-3.4.0'

## Public publish

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: ['test']
        VERSION: ['2.22', '3.0.6', '3.4.0']
...
