---

include:
  - project: veepee/vptech/ci-cd/container-image
    ref: 1-latest
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKERFILE_LINT_EXTRA: --ignore DL3013 --ignore DL3018
  TAG: 4.0.3
...
