---

include:
  - project: veepee/vptech/ci-cd/container-image
    ref: 1-latest
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  APP_VERSION: 5.0.1
  DOCKERFILE_LINT_EXTRA: --ignore DL3013 --ignore DL3018
  DOCKER_BUILD_ARGS: "--build-arg MOLECULE_VERSION=${APP_VERSION}"
  DOCKER_BUILD_HAS_UPSTREAM: "true"

...
