---

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.4.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.1.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 5.0.1
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.10.0
    file: gitlab-ci.yml

stages:
  - lint
  - build
  - publish
  - release

variables:
  APP_NAME: molecule
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'
  SEMANTIC_CONFIG_FILE: changelog

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${CI_COMMIT_REF_SLUG}-${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '3.4.1', '3.5.2' ]

delete-feature:docker:
  variables:
    TAG: '${CI_COMMIT_REF_SLUG}-3.4.1 ${CI_COMMIT_REF_SLUG}-3.5.2'

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg MOLECULE_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '3.4.1', '3.5.2' ]
...
